### ISSUE TITLE
tensorflow:1.4.0 python runtime version warning

### ISSUE THREAD

**Issue by aguegu** [DeftWork/rpi-tensorflow#4]
I noticed that in the elswork/rpi-tensorflow:1.4.0, the python version is 3.5.2. 

And there is a file named `tensorflow-1.4.0-cp35-none-any.whl` in the conntainer root. I supposed it is  the tf installed. 

But when I run models, it would get the runtime warning. 

<img width="732" alt="screen shot 2018-02-27 at 11 03 35" src="https://user-images.githubusercontent.com/1559791/36708617-cd113cae-1bae-11e8-8678-5c091cca16f2.png">

It looks like this wheel package is not built with python3.5, but 3.4. 

Meanwhile, in the readme, v1.4.0 did not use `tensorflow-1.4.0-cp27-none-any.whl`

**Comment by aguegu** [comment]
How about separate dockerfiles by tag? not overwrite the single dockerfile.

**Comment by DeftWork** [comment]
I'm sorry, I believe you are using this docker image https://hub.docker.com/r/elswork/rpi-tensorflow-py3/ which is experimental and it's source code isn't shared yet in github.
This repository is corresponding to this one https://hub.docker.com/r/elswork/rpi-tensorflow/ based on py2.
You are right the wheel file is 3.4, I renamed it in order to be able to install it under python 3.5 this is the reason yo see those warnings, I've followed this instructions https://petewarden.com/2017/08/20/cross-compiling-tensorflow-for-the-raspberry-pi/
If you are interested I will publish the py3 repository and maybe you can help me to fix it.

**Comment by aguegu** [comment]
thank you for your explaining. 

Yes, it is elswork/rpi-tensorflow-py3:1.4.0. I was trying to find some docker-ready TF that I can deploy on my rpi3 and found your repo. 

Maybe I should try compile it on rpi on my own.

**Comment by DeftWork** [comment]
If the use of py3 isn't a constraint I would suggest to you to use this docker image:
https://hub.docker.com/r/elswork/rpi-tensorflow/ Is the last one version of TF and works ok in Raspberry/odroid, ...
Otherwise stay tunned, I will publish soon the py3 experimental version.

**Comment by DeftWork** [comment]
I hope this helps you:

https://github.com/DeftWork/rpi-tensorflow-py3
https://hub.docker.com/r/elswork/rpi-tensorflow-py3/

Pd: There are still the same warnings, but it works.

**Comment by aguegu** [comment]
Thank you
